const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('mapApi', {
  pickFolder: () => ipcRenderer.invoke('pick-folder'),
  scanFolder: (folderPath) => ipcRenderer.invoke('scan-folder', folderPath),
  getPhotos: (options) => ipcRenderer.invoke('get-photos', options),
  getPhotoIds: (options) => ipcRenderer.invoke('get-photo-ids', options),
  listSavedSearches: () => ipcRenderer.invoke('list-saved-searches'),
  saveSavedSearch: (name, query) => ipcRenderer.invoke('save-saved-search', name, query),
  deleteSavedSearch: (id) => ipcRenderer.invoke('delete-saved-search', id),
  getPhotoCount: () => ipcRenderer.invoke('get-photo-count'),
  getMapPoints: () => ipcRenderer.invoke('get-map-points'),
  getPhotoDetail: (id) => ipcRenderer.invoke('get-photo-detail', id),
  updateTags: (id, tags) => ipcRenderer.invoke('update-tags', id, tags),
  batchUpdateTags: (ids, action, value) => ipcRenderer.invoke('batch-update-tags', ids, action, value),
  findSimilar: (id) => ipcRenderer.invoke('find-similar', id),
  getStats: () => ipcRenderer.invoke('get-stats'),
  openFile: (path) => ipcRenderer.invoke('open-file', path),
  showInFolder: (path) => ipcRenderer.invoke('show-in-folder', path),
  saveGeminiKey: (key) => ipcRenderer.invoke('save-gemini-key', key),
  getGeminiKey: () => ipcRenderer.invoke('get-gemini-key'),
  getAiProviders: () => ipcRenderer.invoke('get-ai-providers'),
  getAiConfig: () => ipcRenderer.invoke('get-ai-config'),
  saveAiConfig: (config) => ipcRenderer.invoke('save-ai-config', config),
  testAiConfig: () => ipcRenderer.invoke('test-ai-config'),
  aiTagSingle: (id) => ipcRenderer.invoke('ai-tag-single', id),
  aiTagBatch: (ids) => ipcRenderer.invoke('ai-tag-batch', ids),
  getPhotosPaged: (options) => ipcRenderer.invoke('get-photos-paged', options),
  fixMissingThumbs: () => ipcRenderer.invoke('fix-missing-thumbs'),
  deletePhoto: (id) => ipcRenderer.invoke('delete-photo', id),
  deletePhotoDisk: (id) => ipcRenderer.invoke('delete-photo-disk', id),
  deletePhotoPermanent: (id) => ipcRenderer.invoke('delete-photo-permanent', id),
  toggleStar: (id) => ipcRenderer.invoke('toggle-star', id),
  saveAppSetting: (key, value) => ipcRenderer.invoke('save-app-setting', key, value),
  getRawPreview: (id) => ipcRenderer.invoke('get-raw-preview', id),
  getDisplayPhoto: (id, preferEdited = true, priority = 'normal') =>
    ipcRenderer.invoke('get-display-photo', id, preferEdited, priority === 'low' ? 1 : 0),
  getAppSettings: () => ipcRenderer.invoke('get-app-settings'),
  importWatermarkDialog: () => ipcRenderer.invoke('import-watermark-dialog'),
  getWatermark: () => ipcRenderer.invoke('get-watermark'),
  removeWatermark: () => ipcRenderer.invoke('remove-watermark'),
  applyWatermark: (ids, options) => ipcRenderer.invoke('apply-watermark', ids, options),
  onWatermarkProgress: (callback) => ipcRenderer.on('watermark-progress', (event, data) => callback(data)),
  applyCompression: (ids, options) => ipcRenderer.invoke('apply-compression', ids, options),
  onCompressionProgress: (callback) => ipcRenderer.on('compression-progress', (event, data) => callback(data)),
  softDeletePhoto: (id) => ipcRenderer.invoke('soft-delete-photo', id),
  restorePhoto: (id) => ipcRenderer.invoke('restore-photo', id),
  getDeletedPhotos: () => ipcRenderer.invoke('get-deleted-photos'),
  getTravelRoutes: (dayKey) => ipcRenderer.invoke('get-travel-routes', dayKey),
  getLocationGroups: () => ipcRenderer.invoke('get-location-groups'),
  setGps: (id, lat, lon) => ipcRenderer.invoke('set-gps', id, lat, lon),
  previewBatchRename: (ids, options) => ipcRenderer.invoke('preview-batch-rename', ids, options),
  batchRename: (ids, options) => ipcRenderer.invoke('batch-rename', ids, options),
  onRenameProgress: (callback) => ipcRenderer.on('rename-progress', (event, data) => callback(data)),
  exportHtml: (ids) => ipcRenderer.invoke('export-html', ids),
  getStatistics: () => ipcRenderer.invoke('get-statistics'),
  findBursts: () => ipcRenderer.invoke('find-bursts'),
  importPresetDialog: () => ipcRenderer.invoke('import-preset-dialog'),
  listPresets: () => ipcRenderer.invoke('list-presets'),
  deletePreset: (id) => ipcRenderer.invoke('delete-preset', id),
  previewPhotoEdit: (id, presetId, intensity) => ipcRenderer.invoke('preview-photo-edit', id, presetId, intensity),
  applyPhotoEdit: (id, presetId, intensity) => ipcRenderer.invoke('apply-photo-edit', id, presetId, intensity),
  resetPhotoEdit: (id) => ipcRenderer.invoke('reset-photo-edit', id),
  exportPhotoEdit: (id) => ipcRenderer.invoke('export-photo-edit', id),
  onFixProgress: (callback) => ipcRenderer.on('fix-progress', (event, data) => callback(data)),
  minimizeWindow: () => ipcRenderer.invoke('window-minimize'),
  maximizeWindow: () => ipcRenderer.invoke('window-maximize'),
  closeWindow: () => ipcRenderer.invoke('window-close'),
  onScanProgress: (callback) => ipcRenderer.on('scan-progress', (event, data) => callback(data)),
  onAiTagProgress: (callback) => ipcRenderer.on('ai-tag-progress', (event, data) => callback(data)),
  jobStart: (type, payload, options) => ipcRenderer.invoke('job-start', type, payload, options),
  syncXmp: (ids) => ipcRenderer.invoke('sync-xmp', ids),
  jobList: () => ipcRenderer.invoke('job-list'),
  jobPause: (id) => ipcRenderer.invoke('job-pause', id),
  jobResume: (id) => ipcRenderer.invoke('job-resume', id),
  jobCancel: (id) => ipcRenderer.invoke('job-cancel', id),
  jobRetry: (id) => ipcRenderer.invoke('job-retry', id),
  jobClearFinished: () => ipcRenderer.invoke('job-clear-finished'),
  jobRemove: (id) => ipcRenderer.invoke('job-remove', id),
  onJobsChanged: (callback) => ipcRenderer.on('jobs-changed', () => callback()),
  setRating: (id, rating) => ipcRenderer.invoke('set-rating', id, rating),
  setColorLabel: (id, color) => ipcRenderer.invoke('set-color-label', id, color),
  getPhotoVersions: (id) => ipcRenderer.invoke('get-photo-versions', id),
  activatePhotoVersion: (id, versionId) => ipcRenderer.invoke('activate-photo-version', id, versionId),
  listAlbums: () => ipcRenderer.invoke('list-albums'),
  createAlbum: (name, kind, query) => ipcRenderer.invoke('create-album', name, kind, query),
  deleteAlbum: (id) => ipcRenderer.invoke('delete-album', id),
  addPhotosToAlbum: (albumId, ids) => ipcRenderer.invoke('add-photos-to-album', albumId, ids),
  removePhotoFromAlbum: (albumId, photoId) => ipcRenderer.invoke('remove-photo-from-album', albumId, photoId),
  getAlbumPhotos: (albumId, options) => ipcRenderer.invoke('get-album-photos', albumId, options),
  reverseGeocode: (lat, lon) => ipcRenderer.invoke('reverse-geocode', lat, lon)
});
